    <!-- application/views/scripts/guestbook/index.phtml -->
     
     <?php /*
    <p><a href="<?php echo $this->url(
        array(
            'controller' => 'box',
            'action'     => 'add'
        ),
        'default',
        true) ?>">Add new Box</a></p>
     */ ?>
     
    Boxes: <br />
    <dl>
        <?php foreach ($this->entries as $entry): ?>
		<dt>
		
			<a href='<?php echo "id".$entry->id;?>'><?php echo "http://www." . $_SERVER['SERVER_NAME']. "/".$entry->id;?></a>
			
        	
		</dt>
		<?php
			/* 
	        <dd><?php echo $this->escape($entry->deviceId) ?></dd>
	        <dd><?php echo $this->escape($entry->messageTitle) ?></dd>
	        <dd><?php echo $this->escape($entry->messageBody) ?></dd>
	        <dd><?php echo $this->escape($entry->riddleQuestion) ?></dd>
	        <dd><?php echo $this->escape($entry->riddleAnswer) ?></dd>
	        <dd><?php echo $this->escape($entry->fileName) ?></dd>
	        <dd><?php echo $this->escape($entry->unlockDate) ?></dd>*/
        ?>
        <?php endforeach ?>
    </dl>