<br /><br />
<div id="view-content">	
	<?php if ($this->entry != null && $this->entry->id != null) {?>
	    <dl>
			<dt>
	        	Box #<?php echo $this->entry->id ?>
			</dt>
	        <dd>Device ID: <?php echo $this->entry->deviceId ?></dd>
	        <dd>Message Title: <?php echo $this->entry->messageTitle ?></dd>
	        <dd>Message Body: <?php echo $this->entry->messageBody ?></dd>
	        <dd>Riddle Question: <?php echo $this->entry->riddleQuestion ?></dd>
	        <dd>Riddle Answer: <?php echo $this->entry->riddleAnswer ?></dd>
	        <dd>File Name: <a href="http://<?php echo $this->entry->fileName ?>"> <?php echo $this->entry->fileName ?></a></dd>
	        <dd>Unlock Date: <?php echo $this->entry->unlockDate ?></dd>
	    </dl>	
    <?php } else {
    		echo "box not found";
    	  }
    	 ?>
</div>