<!-- player section -->

<link rel="stylesheet" href="../../css/player/jplayer.blue.monday.css" type="text/css" media="all" />
<link rel="stylesheet" href="../../css/player/main.css" type="text/css" media="all" />

<script src="../../js/player/jquery.min.js" type="text/javascript"></script>
<script src="../../js/player/jquery.jplayer.min.js" type="text/javascript"></script>
<script src="../../js/player/main.js" type="text/javascript"></script>

<!-- end player section -->

<link rel="stylesheet" type="text/css" href="../../css/newlook.css" />
<link rel="icon" type="image/png" href="../../images/icon.png" />

<script type="text/javascript" src="../../js/jquery.jsmovie.js" ></script>

<script>
	jQuery.preloadImages = function () {
			var images = (typeof arguments[0] == 'object') ? arguments[0] : arguments;
			for (var i = 0; i < images.length; i++) {
			jQuery("<img>").attr("src", images[i]);
		}
	};

	$.preloadImages("../../images/postcard.png");
		
	$(document).ready(function(){
		$('#advertisement').jsMovie({
			sequence : "seq##.jpg",    //the #### will be replaced with 0001,0002,0003,...
			folder   : "../../images/sequences/",       //this is the path where the script can find the image sequence
			from     : 1,               //the #### will start to replace with 0001
			to       : 41,              //the #### will start to replace with 0040
			width    : 640,             //the advertisement container will be resized to a width of 320px
			height   : 480,             //the advertisement container will be resized to a height of 150px
			showPreLoader : true,       //we do want to see a preloader animation
			playOnLoad : false,         //we don't want to have the movie play after the images have been loaded automatically
			// the preloader animation is located in the folder "img/loader.png"
			// it is a 4x4 image matrix with each image of 40px by 40px
			loader   : {path:"../../images/loader.png",height:40,width:40,rows:4,columns:4},
			fps: 10
		});
		
		// make frame 1 to frame 20 to a clip an call it Hello. Pause the animation for 2 seconds before the next clip is being played
		//$('#advertisement').jsMovie("addClip","Idle",1,15,2000);
		$('#advertisement').jsMovie("addClip","Open",1,26,2000);
		$('#advertisement').jsMovie("addClip","Close",27,41,2000);
		// play both the clips
		//$('#advertisement').jsMovie("playClip", 0);

	});	

	function showQ()
	{
		$('#intro').hide();
		$('#question').show();
	}
</script>	

<div id="intro">
	<?php
	
	$msg = '';
	$imgurl = 'temp_video.png';
	$show = 0;
	if ($this->entry != null && $this->entry->id != null) {
		$todays_date = date("Y-m-d"); 
		$today = strtotime($todays_date);
		$expiration_date = strtotime($this->entry->unlockDate);
		
		if ($expiration_date > $today) {
			$msg = 'This box opens on' . $this->entry->unlockDate . '!';
			$imgurl = 'box-date.png';
		} else {
			$show = 1;
		}		
	} ?>
	
	  <table width="1020" border="0" align="center" cellpadding="0" cellspacing="0">
	  <tr>
	    <th colspan="3" scope="col"><img src="../../images/top.png" width="1020" height="12" /></th>
	  </tr>
	  <tr>
	    <td width="190"><img src="../../images/left_side.png" width="190" height="480" align="baseline" /></td>
	    <td width="640">
			<img src="../../images/<?php echo $imgurl ?>" width="640" height="480" onclick="<?php if ($show == 1) echo 'showQ()'?>" />
		</td>
	    <td width="190"><img src="../../images/right_side.png" width="190" height="480" /></td>
	  </tr>
	  <tr>
	    <td colspan="3"><img src="../../images/bottom.png" width="1020" height="97" /></td>
	  </tr>	  
	</table>
	
	  <?php if ($show == 0) {?>
		<div id="unlockDateMessage">
		<center>
		This box opens on <?php echo $this->entry->unlockDate; ?> !
		</center>		
		</div>
	  <?php }?>
</div>	
	
<div id="question" style="display: none" align="center">
	
	<table width="1020" border="0" align="center" cellpadding="0" cellspacing="0">
	  <tr>
	    <th colspan="3" scope="col"><img src="../../images/top.png" width="1020" height="12" /></th>
	  </tr>
	  <tr>
	    <td width="190"><img src="../../images/left_side.png" width="190" height="480" align="baseline" /></td>
		<td width="640">
			<div id="advertisement" style="display: none"> </div>
			<!-- Animation sequence must start preloading automatically, user should not see any preloader it should be invisible -->
			<!-- Ideally only if user answered the question and preloader did not finish the loading images it must show -->
			<img id="tempad" src="../../images/temp_video.png" width="640" height="480" />
		</td>
	    <td width="190"><img src="../../images/right_side.png" width="190" height="480" /></td>
	  </tr>
	  <tr>
	    <td colspan="3"><img src="../../images/bottom.png" width="1020" height="97" /></td>
	  </tr>
	</table>
	
	<div id="subquestion">
		<table width="664" height="178px" border="0" align="center" cellpadding="0" cellspacing="0" id="question-form">
			<tr height="65%">
				<td align="center"><p id="question-text"><?php echo $this->entry->riddleQuestion ?></p></td>
			</tr>
			<tr height="35%" valign="top">
				<td align="center">
				
					<form action="" method="post">
						<input type="text" name="name" id="name" placeholder="Your answer" value=""  class="input-field"/>
						<button type="submit" id="submit" class="input-button"></button>
						<center><span id="error" style="display: none; color: red; font-size: 1.6em;">Nope... try again</span></center>
					</form>
				
				</td>
			</tr>
		</table>
	</div>
		<script>
			$("#submit").click(function() {
				$("#error").hide();
				if ($("#name").val().toLowerCase() == "<?php echo $this->entry->riddleAnswer ?>".toLowerCase())	{
					$("#tempad").hide();
					$("#subquestion").hide();
					$('#advertisement').show();
					$("#advertisement").jsMovie("option", "repeat", false);
					$("#advertisement").jsMovie("playClip", 0);
					$("form").hide();
					$('#advertisement').unbind("ended");
					$('#advertisement').bind("ended", function(){			
						$("#question").hide();
						$("#view").show();
						$('#advertisement').hide();
					});
				} else {
					$("#error").show();
				}
				
				return false;
			});			
		</script>
</div>	
	

<div id="view" style="display: none">
	<table width="1020" border="0" align="center" cellpadding="0" cellspacing="0">
	  <tr>
	    <th colspan="3" scope="col"><img src="../../images/top.png" width="1020" height="12" /></th>
	  </tr>
	  <tr>
	    <td width="190"><img src="../../images/left_side.png" width="190" height="480" align="baseline" /></td>
			<?php

			$link = $this->entry->getAmazonFullFileName();

			$filetype = $this->entry->fileType;
			
			$filetype = explode(DIRECTORY_SEPARATOR, $filetype);
			$filetype = $filetype[0];
			
			if ($filetype == "audio") {
			?>
			
			<td width="640" id="postcard">
			
			<script>
			$(document).ready(function(){

			    $("#jquery_jplayer_1").jPlayer({
			        ready: function () {
			            $(this).jPlayer("setMedia", {
			                mp3: "<?php echo $link ?>",
			            }).jPlayer("play"); // auto "play"
			        },
			        //ended: function (event) {
			        //    $(this).jPlayer("play");
			        //},
			        swfPath: "../../swf",
			        supplied: "mp3"
			    })
			    .bind($.jPlayer.event.play, function() { // pause other instances of player when current one play
			            $(this).jPlayer("pauseOthers");
			    });
			});
			</script>
			
	       <div class="players">
	            <div class="jp-audio">
	                <div class="jp-type-single">
	                    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
	                    <div id="jp_interface_1" class="jp-interface">
	                        <ul class="jp-controls">
	                            <li><a href="#" class="jp-play" tabindex="1">play</a></li>
	                            <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
	                            <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
	                            <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
	                            <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
	                        </ul>
	                        <!-- div class="jp-progress">
	                            <div class="jp-seek-bar">
	                                <div class="jp-play-bar"></div>
	                            </div>
	                        </div-->
	                        <div class="jp-mute">
	                            <!-- div class="jp-volume-bar-value"></div-->
	                        </div>
	                        <!-- div class="jp-current-time"></div>
	                        <div class="jp-duration"></div-->
	                    </div>
	                    <div id="jp_playlist_1" class="jp-playlist">
	                    </div>
	                </div>
	            </div>
	        </div>
			        

						<?php }?>
			
			<?php 
			
			if ($filetype == "video" || $filetype == "application") {
			?>
			
			<td width="640" id="postcard">
			
			<script>
			$(document).ready(function(){

			
			    $("#jquery_jplayer_2").jPlayer({
			        ready: function () {
			            $(this).jPlayer("setMedia", {
			                m4v:  "<?php echo $link ?>",
			                //ogv: "../../pl/media/tokyo.ogv",
			                //poster: "../../pl/media/poster.jpg"
			            });
			        },
			        ended: function (event) {
			            $("#jquery_jplayer_2").jPlayer("play", 0);
			        },
			        swfPath: "../../swf",
			        supplied: "m4v", //, ogv",
			        cssSelectorAncestor: "#jp_interface_2"
			    })
			    .bind($.jPlayer.event.play, function() { // pause other instances of player when current one play
			            $(this).jPlayer("pauseOthers");
			    });
			});			    
			</script>
			
	        <div class="players">
	            <div class="jp-video jp-video-270p">
	                <div class="jp-type-single">
	                    <div id="jquery_jplayer_2" class="jp-jplayer"></div>
	                    <div id="jp_interface_2" class="jp-interface">
	                        <div class="jp-video-play"></div>
	                        <ul class="jp-controls">
	                            <li><a href="#" class="jp-play" tabindex="1">play</a></li>
	                            <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
	                            <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
	                            <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
	                            <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
	                        </ul>
	                        <!-- div class="jp-progress">
	                            <div class="jp-seek-bar">
	                                <div class="jp-play-bar"></div>
	                            </div>
	                        </div-->
	                        <div class="jp-mute">
	                            <!-- div class="jp-volume-bar-value"></div-->
	                        </div>
	                        <!-- div class="jp-current-time"></div>
	                        <div class="jp-duration"></div-->
	                    </div>
	                    <div id="jp_playlist_2" class="jp-playlist">
	                    </div>
	                </div>
	            </div>
	
	        </div>
				
			<?php }?>
			 
			<?php
			 
			if ($filetype == "image") { 
			?>
			<td width="640" id="postcard" align="center">
			<img src='<?php echo $link ?>' height="300px"/>
			
			<?php }?>
			
			<p style="text-align: center"><?php echo $this->entry->messageBody ?></p>
		</td>
	    <td width="190"><img src="../../images/right_side.png" width="190" height="480" style="vertical-align:text-top;"/>
		</td>
	  </tr>
	  <tr>
	    <td colspan="3"><img src="../../images/bottom.png" width="1020" height="97" /></td>
	  </tr>
	</table>
	<center>
		<input id="close" type="button" class="close-button" value=""/>
	</center>
		<script>
		$("#close").click(function() {
			$("#view").hide();
			$("#question").show();
			$('#advertisement').show();
			$('#advertisement').unbind("ended");
			$("#advertisement").jsMovie("playClip", 1);
			$('#advertisement').bind("ended", function(){
				$("#question").hide();
				$("#advertisement").hide();
				removeBox();				
			});
		});

		function removeBox() {
			var url='/viewer/remove/?id=' + '<?php echo $this->entry->tag ?>';
			//alert(url);
			window.open(url, "_self");
		}
		</script>				
	<br />		
</div>