<style>

	a:link,
	a:visited
	{
		color: #ffffff;
	}
	
	@font-face {
	    font-family: "Throw My Hands Up in the Air";
	    src: url("fonts/ThrowMyHandsUpintheAir.ttf")
	}
				
	div#main
	{
		background-image:url('images/wood.jpg');
		height: 100%;
		width: 100%;
		position: absolute;
	}
</style>

<div id="main">
    <dl>
        <?php foreach ($this->entries as $viewer): ?>
		<dt>
		
			<?php 
			$boxId = $viewer->getBoxId();
			$viewerId = $viewer->getId();
			$map = new Application_Model_BoxMapper();
			$box = new Application_Model_Box();
				
			$map->find($boxId, $box);

			if ($box->isEmpty()) continue;
			?>
	
			<a href="<?php echo $this->url(array('viewerId' => $viewerId, 'boxId' => $boxId), 'box_route', true) ?>">
				<?php echo "http://www." . $_SERVER['SERVER_NAME']. "/".$viewerId."/".$boxId;?>
			</a>		
			
		</dt>
        <?php endforeach ?>
    </dl>
</div>