<style>

	body {
		margin:0;
		padding:0;
		height:100%;
	}
	
	div#main
	{
		background-image:url('../../images/background.png');
		height:100%;
		width: 100%;
		position: absolute;		
	}
	#card
	{
		background-image:url('../../css/bestanden/card.png');
		background-repeat:no-repeat;
	}
</style>

<link rel="stylesheet" type="text/css" href="'../../css/bestanden/newlook.css">
<link rel="icon" type="image/png" href="http://popthelid.com/images/icon.png">

  </head><body><table align="center" border="0" cellpadding="0" cellspacing="0" width="1020">
  <tbody><tr>
    <th colspan="3" scope="col"><img src="'../../css/bestanden/top.png" height="12" width="1020"></th>
  </tr>
  <tr>
    <td width="190"><img src="'../../css/bestanden/left_side.png" align="bottom" height="480" width="190"></td>
    <td width="640">
		<img src="'../../css/bestanden/main_frame.png" height="480" width="640">
	</td>
    <td width="190"><img src="'../../css/bestanden/right_side.png" height="480" width="190"></td>
  </tr>
  <tr>
    <td colspan="3"><img src="'../../css/bestanden/bottom.png" height="97" width="1020"></td>
  </tr>
</tbody></table>
<table id="card" align="center" border="0" cellpadding="0" cellspacing="0" height="480" width="1020">
<tbody>
<tr><td style="text-align:center"><img src="'../../css/bestanden/logotype.png"></td></tr>
<tr>
	<td align="center" width="640" height="128" style="padding-left:200px;padding-right:200px;">
		<p style="font-family:Amienne;font-size: 2.6em; color: #352b22;">PopTheLid is an app that allows you to wrap and give gifts using your iPhone. You can share your gifts via Facebook or e-mail. It is a fun and an easy way to deliever happiness to your friends and family!</p>
	</td>
</tr>
<tr>
<td style="text-align:center">
<a style="font-size: 2.4em" href="http://store.apple.com/popthelid/download">Download from Apple Store</a>
<br/>
</td>
</tr>
</tbody>
</table>		
<br>
