<style>

	body {
		margin:0;
		padding:0;
		height:100%;
	}
	
	div#main
	{
		background-image:url('../../imgs/background.png');
		height:100%;
		width: 100%;
		position: absolute;		
	}
	#card
	{
		background-image:url('../../css/besta/card.png');
		background-repeat:no-repeat;
	}
</style>

<link rel="stylesheet" type="text/css" href="../../css/besta/newlook.css">
<link rel="icon" type="image/png" href="../../imgs/icon.png">

  </head><body><table align="center" border="0" cellpadding="0" cellspacing="0" width="1020">
  <tbody><tr>
    <th colspan="3" scope="col"><img src="../../css/besta/top.png" height="12" width="1020"></th>
  </tr>
  <tr>
    <td width="190"><img src="../../css/besta/left_side.png" align="bottom" height="480" width="190"></td>
    <td width="640">
		<img src="../../css/besta/main_frame.png" height="480" width="640">
	</td>
    <td width="190"><img src="../../css/besta/right_side.png" height="480" width="190"></td>
  </tr>
  <tr>
    <td colspan="3"><img src="../../css/besta/bottom.png" height="97" width="1020"></td>
  </tr>
</tbody></table>
<table id="card" align="center" border="0" cellpadding="0" cellspacing="0" height="210" width="1020">
<tbody>
<tr><td style="text-align:center"><img src="../../css/besta/logotype.png"></td></tr>
<tr>
	<td align="center" width="640" height="128" style="padding-left:220px;padding-right:220px;">
	<p style="font-family:Amienne;font-size: 2.1em; color: #352b22;">PopTheLid is an app that allows you to wrap and give gifts using your iPhone. You can share your gifts via Facebook or e-mail. It is a fun and an easy way to deliever happiness to your friends and family!</p></td>
</tr>
<tr>
<td style="text-align:left">
<a style="font-size: 2.4em;padding-left:100px;text-decoration:none;" href="http://store.apple.com/popthelid/download">
	<img src="../../css/besta/download-button.png">
</a>
<br/>
</td>
</tr>
</tbody>
</table>
<div style="color:#330000; font-size:0.3em;font-family:arial;text-align:center">
&nbsp;&nbsp;&nbsp<span>2012 M.J. Sala Holding Amsterdam BV</span><span style="color:#ffffff">&nbsp;&nbsp|&nbsp;&nbsp</span><a href="" style="color:#330000;">Terms and conditions</a>
</div>