<style>

	a:link,
	a:visited
	{
		color: #c8d9c5;
		font-family: "Throw My Hands Up in the Air";
		font-size: 18px;
		font-weight: bold; 
		text-decoration: none;
		
	}
	
	body {
		margin:0;
		padding:0;
		height:100%;
	} 	
	
	@font-face {
	    font-family: "Throw My Hands Up in the Air";
	    src: url("../../fonts/ThrowMyHandsUpintheAir.ttf")
	}
				
	div#main
	{
		background-image:url('../../images/wood.jpg');
		height: 100%;
		width: 100%;
		position: absolute;
		padding-top:60px;
	}
</style>

<div id="main">
	<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0">
	<tr><td align="center" valign="top">

    <dl>
        <?php foreach ($this->entries as $viewer): ?>
		<dt>
		
			<?php 
			$boxId = $viewer->getBoxId();
			$viewerId = $viewer->getId();
			$map = new Application_Model_BoxMapper();
			$box = new Application_Model_Box();
				
			$map->find($boxId, $box);

			if ($box->isEmpty()) continue;
			?>
	
			<a href="<?php echo $this->url(array('viewerId' => $viewerId, 'boxId' => $boxId), 'box_route', true) ?>">
				<?php echo "http://www." . $_SERVER['SERVER_NAME']. "/path/".$viewerId."/".$boxId;?>
			</a>		
			
		</dt>
        <?php endforeach ?>
    </dl>
</td></tr></table>    
</div>